#!/bin/bash

echo "Mise à jour et installation des paquets..."
export DEBIAN_FRONTEND=noninteractive
apt update && apt upgrade -y
apt install -y apache2 mariadb-server php libapache2-mod-php php-mysql
curl unzip bind9 exim4 dovecot-imapd roundcube phpmyadmin openssl mutt mailutils
echo

echo "1/2 - Création du VirtualHost HTTP (Redirection)"
cat < /etc/apache2/sites-available/wordpress_tech.conf
<VirtualHost *:80>
ServerName wordpress.tech.lan
ServerAdmin tech@tech.lan
DocumentRoot /var/www/wordpress_tech
<Directory /var/www/wordpress_tech>
AllowOverride All
Require all granted

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

EOF

echo "2/2 - Création du VirtualHost HTTPS (SSL)"
cat < /etc/apache2/sites-available/wordpress_tech-ssl.conf
<VirtualHost *:443>
ServerName wordpress.tech.lan
ServerAdmin tech@tech.lan
DocumentRoot /var/www/wordpress_tech
<Directory /var/www/wordpress_tech>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted

SSLEngine on
SSLCertificateFile /etc/apache2/apache.pem
SSLCertificateKeyFile /etc/apache2/apache.key

EOF
echo

echo "Activation des sites et modules Apache..."
a2enmod ssl rewrite > /dev/null
a2ensite wordpress_tech.conf wordpress_tech-ssl.conf > /dev/null
a2dissite 000-default.conf > /dev/null
ln -sf /etc/roundcube/apache.conf /etc/apache2/conf-available/roundcube.conf
a2enconf roundcube phpmyadmin > /dev/null
echo

echo "Création de la base de données MariaDB..."
mariadb <<EOF
CREATE DATABASE IF NOT EXISTS tech_db;
CREATE USER IF NOT EXISTS 'tech'@'localhost' IDENTIFIED BY "tech$";
GRANT ALL PRIVILEGES ON tech_db.* TO 'tech'@'localhost';
FLUSH PRIVILEGES;
EOF
echo

echo "Téléchargement et installation de Wordpress..."
cd /var/www
rm -f latest-fr_FR.zip
wget -q https://fr.wordpress.org/latest-fr_FR.zip
unzip -q -o latest-fr_FR.zip

On renomme le dossier wordpress en wordpress_tech pour correspondre au Vhost
rm -rf wordpress_tech
mv wordpress wordpress_tech
rm -f latest-fr_FR.zip
echo

echo "Configuration de Wordpress avec SED..."
cd /var/www/wordpress_tech
cp wp-config-sample.php wp-config.php
sed -i 's/database_name_here/tech_db/g' wp-config.php
sed -i 's/username_here/tech/g' wp-config.php
sed -i 's/password_here/tech$/g' wp-config.php

Permissions
chown -R www-data:www-data /var/www/wordpress_tech
chmod -R 755 /var/www/wordpress_tech

Fin de l'installation et envoi du mail
echo "📧 Envoi du mail récapitulatif..."

mail tech@tech.lan -s "Votre site Wordpress" << EOF
L'installation de votre site wordpress est terminée et doit être finalisée sur https://wordpress.tech.lan.
Cordialement,
L'administrateur Tech.
EOF

echo
echo "--------------------------------------------------------------------"
echo " Installation terminée ! Vérifie tes mails (Mutt ou Roundcube)."
echo "--------------------------------------------------------------------"

echo "--------------------------------------------------------------------"
echo " Installation effectuée avec succès !"
echo "--------------------------------------------------------------------"
echo " Accès Web : https://wordpress.tech.lan"
echo "--------------------------------------------------------------------"
