#!/bin/bash

user="bob"
pass="robert"

useradd $user -m -s /bin/bash
echo $user:$pass | chpasswd 2>/dev/null

echo "Téléchargement et installation de la dernière version de wordpress..."
echo

# Téléchargement de wordpress français latest
cd /tmp
rm -f latest-fr_FR.zip
wget https://fr.wordpress.org/latest-fr_FR.zip

# Décompression de wordpress
unzip -q -o latest-fr_FR.zip

# Installation dans le site de l'utilisateur
mv wordpress /var/www/$user

# On se déplace dans /var/www
cd /var/www
# Changement propriétaire wordpress
chown -R $user:user $user/

# Ecriture du virtual host Apache
cat > /etc/apache2/sites-available/$user.conf << EOF
<VirtualHost *:80>
        ServerName $user.tech.lan
        DocumentRoot /var/www/$user
	<Directory /var/www/$user>
		AllowOverride All
	</Directory>
	RewriteEngine On
	RewriteCond %{HTTPS} off
	RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
EOF

# Ecriture du virtual host SSL Apache
cat > /etc/apache2/sites-available/${user}-ssl.conf << EOF
<VirtualHost *:443>
        ServerName $user.tech.lan
        DocumentRoot /var/www/$user
	<Directory /var/www/$user>
		AllowOverride All
	</Directory>
	SSLEngine on
	SSLCertificateFile      /etc/apache2/apache.pem
	SSLCertificateKeyFile   /etc/apache2/apache.key
</VirtualHost>
EOF

# Activation des virtualhost wordpress
a2ensite $user > /dev/null
a2ensite ${user}-ssl > /dev/null

# Rechargement Apache
systemctl reload apache2

# Création de la base de données wordpress
mariadb << EOF
create database if not exists $user; 
create user if not exists ${user}@localhost identified by "$pass";
grant all privileges on ${user}.* to ${user}@localhost;
flush privileges;
EOF

# Remplissage du fichier wp-config.php
cp ${user}/wp-config-sample.php ${user}/wp-config.php
sed -i "s/database_name_here/${user}/" ${user}/wp-config.php
sed -i "s/username_here/${user}/" ${user}/wp-config.php
sed -i "s/password_here/${pass}/" ${user}/wp-config.php


# Fin de l'installation
mail ${user}@tech.lan -s "Votre site Wordpress" << EOF
Bonjour,
L'installation de votre site wordpress est terminée et doit être finalisée sur https://${user}.tech.lan.
Cordialement,
Vous avez accés a vos mails sur htpps://${user}.tech.lan/rondcube et a votre base de données sur https://${user}.tech.lan/phpmyadmin
login $user
mot de passe $pass
EOF
